from __future__ import annotations

from trader_shared.config import (
    LOOKBACK_DAYS,
    RECENT_WINDOW,
    CONFIRM_BUFFER,
    STOP_BUFFER,
    TAKE_PROFIT_BUFFER,
    STATUS_SCORE,
    MA_PERIODS,
    MA_WEIGHTS,
    MIN_ZONE_WIDTH_PCT,
    MAX_ZONE_WIDTH_PCT,
    MIN_STOP_BUFFER_PCT,
    MAX_STOP_BUFFER_PCT,
    MIN_CONFIRM_SPACE_PCT,
    MAX_REASONABLE_MA_DISTANCE_PCT,
    STRUCTURE_WINDOW,
    CHANGE_THRESHOLD_STRONG,
    CHANGE_THRESHOLD_LARGE,
    CHANGE_THRESHOLD_LARGE_DROP,
    CHANGE_THRESHOLD_DROP,
    POSITION_RATIO_STRONG,
    POSITION_RATIO_CONFIRM,
    POSITION_RATIO_HIGH,
    ATR_HIGH_THRESHOLD,
    ATR_ELEVATED_THRESHOLD,
    ATR_NORMAL_THRESHOLD,
    PYRAMID_SCALES,
    BASE_WEIGHTS,
    ATRLV_INDEX,
)

T0_POSITION_SPLIT: float = 0.55
DEFAULT_MAX_TOTAL: int = 80
DEFAULT_CASH_FLOOR: int = 20
DEFAULT_MAIN_CAP: int = 50
