from __future__ import annotations

from trader_shared.config import (
    LOOKBACK_DAYS,
    RECENT_WINDOW,
)

STRUCTURE_WINDOW: int = 20
MIN_5M_BARS: int = 20
MACD_WARMUP_BARS: int = 35
MIN_TRIGGER_MATCHES: int = 4
STRONG_TRIGGER_MATCHES: int = 5
MIN_T_AMPLITUDE_PCT: float = 0.015
GOOD_T_AMPLITUDE_PCT: float = 0.03
MIN_T_NET_SPACE_PCT: float = 0.006
MIN_SELL_NET_SPACE_PCT: float = 0.004
ZONE_MAX_WIDTH_PCT: float = 0.006
ZONE_AMPLITUDE_FACTOR: float = 0.15
DEFAULT_ZONE_WIDTH_PCT: float = 0.005
BUY_CONFIRM_FACTOR: float = 1.002
SELL_CONFIRM_FACTOR: float = 0.998
BUY_ACCEPT_FACTOR: float = 1.003
SELL_ACCEPT_FACTOR: float = 0.997
INVALID_BELOW_SUPPORT: float = 0.995
INVALID_ABOVE_RESISTANCE: float = 1.005
VOLUME_SHRINK_RATIO: float = 0.8
VOLUME_EXPAND_RATIO: float = 1.2
PRICE_TICK: float = 0.01
ENABLE_ICT_EXECUTION: bool = True
ICT_SWEEP_LOOKBACK: int = 8
ICT_RECENT_WINDOW: int = 6
ICT_STRUCTURE_LOOKBACK: int = 3
ATR_STOP_FACTOR: float = 2.0
ATR_STOP_MIN_PCT: float = 0.005
ATR_STOP_MAX_PCT: float = 0.025
ADX_STRONG_THRESHOLD: float = 25.0
ADX_WEAK_THRESHOLD: float = 20.0
